steps:
 # build the container 
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '--network=cloudbuild','-t', 'gcr.io/tough-bearing-364504/nextjs-cloud-run', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/tough-bearing-364504/nextjs-cloud-run']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['run', 'deploy', 'academy-nextjs-cloud-run', '--image', 'gcr.io/tough-bearing-364504/nextjs-cloud-run', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images: 
- 'gcr.io/tough-bearing-364504/nextjs-cloud-run'