steps:
# build the container image
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tough-bearing-364504/nextjs-cloud-run:latest', '.']

# push the container image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tough-bearing-364504/nextjs-cloud-run:latest']

# Deploy container image to Cloud Run
#- name: "gcr.io/cloud-builders/gcloud"
#  args: ['run', 'deploy', 'nextjs-cloud-run', '--image', 'gcr.io/tough-bearing-364504/nextjs-cloud-run', '--region', 'europe-west4', '--platform', 'managed', '--allow-unauthenticated']